import { MapTemplate } from '../types/mapEditor';

/**
 * Hazır harita şablonları
 * generatorType: 'procedural' → bilinen iyi seed ile üretilir
 * terrainData boş → runtime'da generateMap ile üretilir
 */
export const PRESET_MAPS: MapTemplate[] = [
  {
    id: 'random',
    name: 'Rastgele Dunya',
    description: 'Her seferinde farkli, prosedural uretilmis benzersiz harita',
    icon: '🎲',
    author: 'system',
    createdAt: 0,
    radius: 18,
    playerCount: 4,
    startPositions: [],
    terrainData: [],
    generatorType: 'procedural',
    tags: ['rastgele', 'dengeli'],
  },
  {
    id: 'island_world',
    name: 'Ada Dunyasi',
    description: 'Denizlerle cevrili buyuk bir kita adasi. Kiyilarda ticaret, ic kesimlerde savas.',
    icon: '🏝️',
    author: 'system',
    createdAt: 0,
    radius: 18,
    playerCount: 4,
    startPositions: [],
    terrainData: [],
    generatorType: 'procedural',
    generatorSeed: 42424242,
    tags: ['ada', 'dengeli', 'kiyi'],
  },
  {
    id: 'big_continent',
    name: 'Buyuk Kita',
    description: 'Genis kara kutlesi, uzun kiyi seritleri, ic denizler ve dag zincirleri.',
    icon: '🌍',
    author: 'system',
    createdAt: 0,
    radius: 22,
    playerCount: 4,
    startPositions: [],
    terrainData: [],
    generatorType: 'procedural',
    generatorSeed: 77889900,
    tags: ['kita', 'buyuk', 'dengeli'],
  },
  {
    id: 'archipelago',
    name: 'Takimadalar',
    description: 'Kucuk adalar zinciri. Her oyuncu kendi adasindan baslar, deniz kontrol kritik.',
    icon: '🗺️',
    author: 'system',
    createdAt: 0,
    radius: 20,
    playerCount: 4,
    startPositions: [],
    terrainData: [],
    generatorType: 'procedural',
    generatorSeed: 11223344,
    tags: ['ada', 'deniz', 'stratejik'],
  },
  {
    id: 'desert_empire',
    name: 'Col Imparatorlugu',
    description: 'Genis coller, vaha noktalari, kuzey orman kusagi. Kaynaklar icin mucadele.',
    icon: '🏜️',
    author: 'system',
    createdAt: 0,
    radius: 18,
    playerCount: 3,
    startPositions: [],
    terrainData: [],
    generatorType: 'procedural',
    generatorSeed: 55667788,
    tags: ['col', 'kaynak', 'zor'],
  },
  {
    id: 'frozen_north',
    name: 'Donmus Kuzey',
    description: 'Daglarla cevrili soguk topraklar, yogun ormanlar, sinirli tarim alanlari.',
    icon: '❄️',
    author: 'system',
    createdAt: 0,
    radius: 16,
    playerCount: 3,
    startPositions: [],
    terrainData: [],
    generatorType: 'procedural',
    generatorSeed: 99001122,
    tags: ['dag', 'orman', 'zor'],
  },
];
